# Generated by Django 5.1.2 on 2024-12-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='entity',
            field=models.CharField(choices=[('post', 'post'), ('comment', 'comment')], default='a', max_length=10),
            preserve_default=False,
        ),
    ]
