# Generated by Django 5.1.2 on 2024-11-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descriptiomn',
            new_name='description',
        ),
    ]
