# Generated by Django 5.1.4 on 2024-12-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_date_post_parent'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic_post_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('topic', 'topic_post_id')},
        ),
    ]
