# Generated by Django 5.1.4 on 2024-12-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_topic_post_id_alter_post_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic_post_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
